servo_dt: 0.00125

ip_address: "tcp://127.0.0.1:5557"

#data_save_freq: 1
data_save_freq: 50

b_sim: true ## if false, all the "exp_" parameters are used
# b_sim: false ## if false, all the "exp_" parameters are used


wbc:
  task:
    ee_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f1_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f2_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]
    
    f3_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    ee_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f1_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f2_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f3_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [1000., 1000., 1000.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    # Force Task (TODO: change to Three Finger Task)
    rf_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [1000., 1000., 1000.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]


  contact:
    ########################################################################
    ## sim params
    ########################################################################
    sim_max_rf_z: 400.
    sim_mu: 0.4

    ########################################################################
    ## exp params
    ########################################################################
    exp_max_rf_z: 400.

    exp_mu: 0.4

  qp:
    b_save_costs: true
    lambda_qddot: 5e-6 ##regularization
    # TODO: 3 finger regularization
    lambda_rf: [1e-3, 1e-3, 1e-3, 1e-5, 1e-5, 1e-5, 1e-3, 1e-3, 1e-3, 1e-5, 1e-5, 1e-5]  #regulariztion lfoot / rfoot (trq, force order)
    b_trq_limit: false


