servo_dt: 0.001

ip_address: "tcp://127.0.0.1:5557"

#data_save_freq: 1
data_save_freq: 50

b_sim: true ## if false, all the "exp_" parameters are used
# b_sim: false ## if false, all the "exp_" parameters are used


wbc:
  task:
    jpos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [100., 100., 100., 100., 100., 100., 100.]
      sim_weight_min : [1., 1., 1., 1., 1., 1., 1.]
      sim_kp : [200., 200., 200., 200., 200., 200., 200.]
      sim_kd : [10., 10., 10., 10., 10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0., 0., 0., 0., 0.]
      exp_weight_at_contact : [0., 0., 0., 0., 0., 0., 0.]
      exp_kp : [100., 100., 100., 100., 100., 100., 100.]
      exp_kd : [10., 10., 10., 10., 10., 10., 10.]

    ee_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [100., 100., 100.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [100., 100., 100.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_weight_at_contact : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f1_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f2_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_weight_at_contact : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]
    
    f3_pos_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    ee_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [100., 100., 100.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [500., 500., 500.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_weight_at_contact : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f1_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f2_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    f3_ori_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0.]
      sim_weight_min : [0., 0., 0.]
      sim_kp : [200., 200., 200.]
      sim_kd : [10., 10., 10.]

      ########################################################################
      ## exp params [TODO: change to real gains]
      ########################################################################
      exp_weight : [0., 0., 0.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 10.]

    upper_body_task:
      ########################################################################
      ## sim params
      ########################################################################
      ## l_shoulder_fe(0), l_shoulder_aa(1), l_shoulder_ie(2), l_elbow_fe(3), l_wrist_ps_(4),
      ## l_wrist_pitch(5), neck_pitch(6), r_shoulder_fe(7), r_shoulder_aa(8), r_shoulder_ie(9),
      ## r_shoulder_ie(10), r_elbow_fe(11), r_wrist_ps(12), r_wrist_pitch(13)
      sim_weight : [40., 40., 40., 40., 40., 40., 40.]
      sim_kp : [100. , 100., 100., 100., 100., 100., 100.]
      sim kd: [10., 10., 10., 10., 10., 10., 10.]


    rf_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0., 1e-8, 1e-8, 5e-10] ## trq, force order

    ee_rf_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0., 1e-8, 1e-8, 5e-10] ## trq, force order
    
    f1_rf_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0., 1e-8, 1e-8, 5e-10] ## trq, force order  
    
    f2_rf_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0., 1e-8, 1e-8, 5e-10] ## trq, force order 
    
    f3_rf_task:
      ########################################################################
      ## sim params
      ########################################################################
      sim_weight : [0., 0., 0., 1e-8, 1e-8, 5e-10] ## trq, force order



  contact:
    ########################################################################
    ## sim params
    ########################################################################
    sim_max_rf_z: 400.

    sim_mu: 0.4

    sim_foot_half_length: 0.08
    sim_foot_half_width: 0.04 ## 0.04

    ########################################################################
    ## exp params
    ########################################################################
    exp_max_rf_z: 400.

    exp_mu: 0.4

    exp_foot_half_length: 0.08
    exp_foot_half_width: 0.04 ## 0.04

  qp:
    b_save_costs: false
    lambda_qddot: 5e-6 ##regularization
    # TODO: 3 finger regularization
    lambda_rf: [1e-3, 1e-3, 1e-3, 1e-5, 1e-5, 1e-5, 1e-3, 1e-3, 1e-3, 1e-5, 1e-5, 1e-5]  #regulariztion lfoot / rfoot (trq, force order)
    b_trq_limit: false

  joint_integrator:
    pos_cutoff_freq: 2.0 #hz
    vel_cutoff_freq: 2. #hz
    max_pos_err: 0.2 #rad



state_machine:
  initialize:
    init_duration: 2.
    wait_time: 0. 
    target_joint_pos: [-0.15,-0.78, -0.34, 1.7, 0.11, 1.135, 0.54]
    b_stay_here: false
    task_transit_time: 0.3

  task_transition:
    duration: 0.01
    wait_time: 0.
    b_stay_here: false
   
  ee_traj:
    duration: 1.
    wait_time: 0.
    target_pos: [0.1, 0.0, 0.8] # x, y, z
    target_ori: [1.0, 0.0, 0.0, 0.0] # w, x, y, z
    b_stay_here: true
