/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int draco3_crbi_helper(const casadi_real **arg, casadi_real **res,
                       casadi_int *iw, casadi_real *w, int mem);
int draco3_crbi_helper_alloc_mem(void);
int draco3_crbi_helper_init_mem(int mem);
void draco3_crbi_helper_free_mem(int mem);
int draco3_crbi_helper_checkout(void);
void draco3_crbi_helper_release(int mem);
void draco3_crbi_helper_incref(void);
void draco3_crbi_helper_decref(void);
casadi_int draco3_crbi_helper_n_in(void);
casadi_int draco3_crbi_helper_n_out(void);
casadi_real draco3_crbi_helper_default_in(casadi_int i);
const char *draco3_crbi_helper_name_in(casadi_int i);
const char *draco3_crbi_helper_name_out(casadi_int i);
const casadi_int *draco3_crbi_helper_sparsity_in(casadi_int i);
const casadi_int *draco3_crbi_helper_sparsity_out(casadi_int i);
int draco3_crbi_helper_work(casadi_int *sz_arg, casadi_int *sz_res,
                            casadi_int *sz_iw, casadi_int *sz_w);
#define draco3_crbi_helper_SZ_ARG 10
#define draco3_crbi_helper_SZ_RES 2
#define draco3_crbi_helper_SZ_IW 0
#define draco3_crbi_helper_SZ_W 5626
int jac_draco3_crbi_helper(const casadi_real **arg, casadi_real **res,
                           casadi_int *iw, casadi_real *w, int mem);
int jac_draco3_crbi_helper_alloc_mem(void);
int jac_draco3_crbi_helper_init_mem(int mem);
void jac_draco3_crbi_helper_free_mem(int mem);
int jac_draco3_crbi_helper_checkout(void);
void jac_draco3_crbi_helper_release(int mem);
void jac_draco3_crbi_helper_incref(void);
void jac_draco3_crbi_helper_decref(void);
casadi_int jac_draco3_crbi_helper_n_in(void);
casadi_int jac_draco3_crbi_helper_n_out(void);
casadi_real jac_draco3_crbi_helper_default_in(casadi_int i);
const char *jac_draco3_crbi_helper_name_in(casadi_int i);
const char *jac_draco3_crbi_helper_name_out(casadi_int i);
const casadi_int *jac_draco3_crbi_helper_sparsity_in(casadi_int i);
const casadi_int *jac_draco3_crbi_helper_sparsity_out(casadi_int i);
int jac_draco3_crbi_helper_work(casadi_int *sz_arg, casadi_int *sz_res,
                                casadi_int *sz_iw, casadi_int *sz_w);
#define jac_draco3_crbi_helper_SZ_ARG 11
#define jac_draco3_crbi_helper_SZ_RES 12
#define jac_draco3_crbi_helper_SZ_IW 0
#define jac_draco3_crbi_helper_SZ_W 11326
#ifdef __cplusplus
} /* extern "C" */
#endif
