iterations_btw_mpc: 40

gait:
  x_vel_cmd: 0.3 ## 0.5
  y_vel_cmd: 0.0
  yaw_rate_cmd: 0.3

  ## TODO: making this as interrupt keystroke
  ## 0: standing
  ## 1: walking
  gait_number: 1

swing_foot:
  height: 0.15
