b_save_mpc_solution: true

iterations_btw_mpc: 40

mpc_params:
  mpc_cost:
    #Qqq: [1e3, 1e3, 1e5, 1e3, 1e3, 1e7] ## roll, pitch, yaw, x, y, z
    #Qvv: [1e1, 1e1, 1e2, 1e1, 1e1, 1e4] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-5, 1e-5, 5e-6, 1e-6, 1e-6, 1e-7] ## trq_x, trq_y, trq_z, fx, fy, fz

    #Qqq: [100, 100, 200, 2000, 2000, 5000000] ## roll, pitch, yaw, x, y, z
    #Qvv: [500, 10, 20, 500, 500, 500000] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-4, 1e-4, 5e-4, 1e-5, 1e-5, 1e-8] ## trq_x, trq_y, trq_z, fx, fy, fz

    #Qqq: [100, 100, 200, 2000, 2000, 1000000] ## roll, pitch, yaw, x, y, z
    #Qvv: [500, 10, 20, 500, 500, 100000] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-5, 1e-5, 1e-5, 1e-5, 1e-5, 1e-5] ## trq_x, trq_y, trq_z, fx, fy, fz
    #
    #Qqq: [1000, 1000, 2000, 2000, 2000, 1000000] ## roll, pitch, yaw, x, y, z
    #Qvv: [500, 500, 500, 500, 500, 100000] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-5, 1e-5, 1e-5, 1e-5, 1e-5, 1e-5] ## trq_x, trq_y, trq_z, fx, fy, fz
    #
    #Qqq: [10, 10, 200, 100, 100, 1000000] ## roll, pitch, yaw, x, y, z
    #Qvv: [5, 5, 50, 20, 20, 100000] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-5, 1e-5, 1e-5, 1e-5, 1e-5, 1e-5] ## trq_x, trq_y, trq_z, fx, fy, fz
    #
    #
    #Qqq: [50, 50, 300, 100, 100, 1000000] ## roll, pitch, yaw, x, y, z
    #Qvv: [20, 20, 150, 30, 30, 10000] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-5, 1e-5, 1e-5, 1e-5, 1e-5, 1e-5] ## trq_x, trq_y, trq_z, fx, fy, fz

    Qqq: [100, 100, 150, 200, 200, 1000000] ## roll, pitch, yaw, x, y, z
    Qvv: [1, 1, 1, 1, 1, 500000] ## wx, wy, wz, xdot, ydot, zdot
    Quu: [1e-2, 1e-2, 1e-2, 1e-4, 1e-4, 5e-4] ## trq_x, trq_y, trq_z, fx, fy, fz

    Qqq_terminal: [10000, 10000, 10000, 10000, 10000, 10000]
    Qvv_terminal: [5000, 5000, 5000, 5000, 5000, 5000]
    decay_rate: 1.0

  nominal_inertia: [ 4.51486, -0.00153135, 0.885743, -0.00153135, 4.1509,
      -0.00292598, 0.885743, -0.00292598, 1.23588 ]

  contact_wrench_cone:
    mu: 0.3
    fz_min: 20.0 #[N]
    fz_max: 600 #[N]
    foot_half_length: 0.08 #[m]
    foot_half_width: 0.04 #[m]


swing_foot:
  height: 0.10
  raibert_gain: 0.02
  high_speed_turning_gain: 1.0

gait:
  x_vel_cmd: 0.0 ## 0.5
  y_vel_cmd: 0.0
  yaw_rate_cmd: 0.0

  ## TODO: making this as interrupt keystroke
  ## 0: standing
  ## 1: walking
  gait_number: 1

