b_save_mpc_solution: true

iterations_btw_mpc: 40

mpc_params:
  mpc_cost:
    #Qqq: [1e3, 1e3, 1e5, 1e3, 1e3, 1e7] ## roll, pitch, yaw, x, y, z
    #Qvv: [1e1, 1e1, 1e2, 1e1, 1e1, 1e4] ## wx, wy, wz, xdot, ydot, zdot
    #Quu: [1e-5, 1e-5, 5e-6, 1e-6, 1e-6, 1e-8] ## trq_x, trq_y, trq_z, fx, fy, fz

    Qqq: [100, 100, 150, 200, 500, 10000] ## roll, pitch, yaw, x, y, z
    Qvv: [1, 1, 10, 10, 50, 2000] ## wx, wy, wz, xdot, ydot, zdot
    Quu: [5e-4, 5e-4, 6e-4, 1e-5, 1e-5, 1e-6] ## trq_x, trq_y, trq_z, fx, fy, fz

  nominal_inertia: [ 4.51486, -0.00153135, 0.885743, -0.00153135, 4.1509,
      -0.00292598, 0.885743, -0.00292598, 1.23588 ]

  contact_wrench_cone:
    mu: 0.5
    fz_min: 20.0 #[N]
    fz_max: 600 #[N]
    foot_half_length: 0.08 #[m]
    foot_half_width: 0.04 #[m]



gait:
  x_vel_cmd: 0.0 ## 0.5
  y_vel_cmd: 0.0
  yaw_rate_cmd: 0.0

  ## TODO: making this as interrupt keystroke
  ## 0: standing
  ## 1: walking
  gait_number: 1

swing_foot:
  height: 0.15
