name: tests
on:
  push:
    branches:
      - main
      - 'feature/add-ci-workflows'
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with: 
          activate-environment: rpc
          auto-update-conda: true
          environment-file: rpc.yml
          auto-activate-base: false
      - name: Activate and build rpc
        shell: bash -l {0}
        run: |
          conda activate rpc
          conda install conda-forge::eigenpy
          conda list
          ./dependency/scripts/install_gtest.sh
          ./dependency/scripts/install_gh_pinocchio.sh
          export PATH=/opt/openrobots/bin:$PATH
          export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=/opt/openrobots/lib/python3.9/site-packages:$PYTHONPATH # Adapt your desired python version here
          export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
          echo "PATH: " $PATH
          echo "PKG_CONFIG_PATH: " $PKG_CONFIG_PATH
          export CMAKE_PREFIX_PATH=/usr/local/include:$CMAKE_PREFIX_PATH
          mkdir build && cd build && cmake .. && make 
