name: tests
on:
  push:
    branches:
      - main
      - 'feature/add-ci-workflows'
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: |
          ./dependency/scripts/install_gtest.sh
          ./dependency/scripts/install_protobuf.sh && ./dependency/scripts/install_zmq.sh
          conda env create -f rpc.yml
          ./dependency/scripts/install_gh_pinocchio.sh
          export CMAKE_PREFIX_PATH=/usr/local/include:$CMAKE_PREFIX_PATH
          mkdir build && cd build && cmake .. && make 
