name: tests
on:
  push:
    branches:
      - main
      - 'feature/add-ci-workflows'
jobs:
  build-simple-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with: 
          activate-environment: rpc
          auto-update-conda: true
          environment-file: rpc.yml
          auto-activate-base: false
      - name: Activate and build base rpc
        shell: bash -l {0}
        run: |
          conda activate rpc
          conda install conda-forge::eigenpy
          pip install conan
          echo ' ------- Installed Conan -------'
          # conan create . -pr=./.github/conan_profile
          echo ' ------- Conan Profile successfully created -------'
          conan install conanfile.txt --build=missing && cd build/ && cmake .. && make
          ./dependency/scripts/install_gtest.sh
          ./dependency/scripts/install_gh_pinocchio.sh
          export PATH=/opt/openrobots/bin:$PATH
          export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=/opt/openrobots/lib/python3.9/site-packages:$PYTHONPATH # Adapt your desired python version here
          export CMAKE_PREFIX_PATH=/opt/openrobots:/usr/local/include:$CMAKE_PREFIX_PATH
          mkdir build && cd build && cmake .. -DBUILD_WITH_ZMQ_PROTOBUF=OFF -DBUILD_WITH_FOXGLOVE=OFF && make
      - name: Run base rpc tests
        shell: bash -l {0}
        run: |
          ./build/bin/ihwbc_test
          ./build/bin/friction_compensator_test
          ./build/bin/dcm_planner_test
          ./build/bin/lmpc_handler_test
          ./build/bin/pin_robot_system_test
      - name: Build rpc with debug tools
        shell: bash -l {0}
        run: |
          ./dependency/scripts/install_protobuf.sh
          ./dependency/scripts/install_zmq.sh
          mkdir build_ui && cd build_ui && cmake .. -DBUILD_WITH_ZMQ_PROTOBUF=ON -DBUILD_WITH_FOXGLOVE=ON && make
