name: tests
on:
  push:
    branches:
      - main
      - 'feature/add-ci-workflows'
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with: 
          activate-environment: rpc
          audo-update-conda: true
          environment-file: rpc.yml
          auto-activate-base: false
      - name: Activate and build rpc
        shell: bash -l {0}
        run: |
          conda activate rpc
          conda list
          ./dependency/scripts/install_gtest.sh
          ./dependency/scripts/install_protobuf.sh && ./dependency/scripts/install_zmq.sh
          ./dependency/scripts/install_gh_pinocchio.sh
          export CMAKE_PREFIX_PATH=/usr/local/include:$CMAKE_PREFIX_PATH
          mkdir build && cd build && cmake .. && make 
