name: tests
on:
  push:
    branches:
      - main
      - 'develop'
      - 'feature/foxglove-ui'
jobs:
  build-base-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rpc
          auto-update-conda: true
          environment-file: rpc.yml
          auto-activate-base: false
      - name: Activate and build base rpc
        shell: bash -l {0}
        run: |
          conda activate rpc
          conda install conda-forge::eigenpy
          ./dependency/scripts/install_gtest.sh
          ./dependency/scripts/install_gh_pinocchio.sh
          export PATH=/opt/openrobots/bin:$PATH
          export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=/opt/openrobots/lib/python3.9/site-packages:$PYTHONPATH
          export CMAKE_PREFIX_PATH=/opt/openrobots:/usr/local/include:$CMAKE_PREFIX_PATH
          mkdir build && cd build && cmake .. -DBUILD_WITH_ZMQ_PROTOBUF=OFF -DBUILD_WITH_FOXGLOVE=OFF -DBUILD_WITH_GTESTS=ON && make
      - name: Run base rpc tests
        shell: bash -l {0}
        run: |
          ./build/bin/ihwbc_test
          ./build/bin/friction_compensator_test
          ./build/bin/dcm_planner_test
          ./build/bin/pin_robot_system_test

  build-with-ui:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rpc
          auto-update-conda: true
          environment-file: rpc.yml
          auto-activate-base: false
      - name: Build rpc with UI
        shell: bash -l {0}
        run: |
          conda activate rpc
          conda install conda-forge::eigenpy
          ./dependency/scripts/install_protobuf.sh
          ./dependency/scripts/install_zmq.sh
          ./dependency/scripts/install_gtest.sh
          ./dependency/scripts/install_gh_pinocchio.sh
          export PATH=/opt/openrobots/bin:$PATH
          export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=/opt/openrobots/lib/python3.9/site-packages:$PYTHONPATH
          export CMAKE_PREFIX_PATH=/opt/openrobots:/usr/local/include:$CMAKE_PREFIX_PATH
          ./dependency/scripts/install_zmq.sh
          ./dependency/scripts/install_protobuf.sh
          pip install conan
          mkdir -p ~/.conan2/profiles/ && cp .github/conan_profile ~/.conan2/profiles/default
          conan install conanfile.txt --build=missing && cd build/ && cmake .. -DBUILD_WITH_ZMQ_PROTOBUF=ON -DBUILD_WITH_FOXGLOVE=ON && make
